require('core')
require('core.remap')
require('plugins.lazy')
require('plugins.configs.telescope')
require('plugins.configs.tokyo')
require('plugins.configs.lualine')
require('plugins.configs.nvim-zero')
